# Generated by Django 2.1.4 on 2020-04-25 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200425_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='BirthDate',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 20, 2, 27, 813671, tzinfo=utc)),
        ),
    ]
