# Generated by Django 2.1.4 on 2020-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200425_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='BirthDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
