# Generated by Django 2.1.4 on 2020-04-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200425_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='BirthDate',
            field=models.DateField(null=True),
        ),
    ]
