# Generated by Django 2.1.4 on 2020-04-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200429_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('INTP', 'INTP'), ('ENTB', 'ENTB'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ'), ('INFP', 'INFP'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ISFP', 'ISFP'), ('ESFP', 'ESFP')], default='XXXX', max_length=4),
        ),
    ]
