# Generated by Django 2.1.4 on 2020-04-29 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200429_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Essays', to=settings.AUTH_USER_MODEL),
        ),
    ]
