# Generated by Django 2.1.4 on 2020-05-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200514_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ParentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comments'),
        ),
    ]
